### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [xancbiz/TeaCozy#5]
Grade: Meets Expectations

Summary: 
Great job on the Tea Cozy project! The only visual difference I saw on your project versus the spec was the fixed header although it seems you commented out the CSS to make it fixed. You did an excellent job documenting your HTML which adds to its readability and did an excellent job using various HTML tags like the figcaption. 

One thing to consider as you work on future projects is commenting your CSS file a bit more and adequately indenting your HTML file. An adequately indented HTML file makes it easier to understand how different elements are nested and where different divs start and end. This all just makes the file easier to read which increases collaboration once you start working in a team.  

For extra practice consider going over this sample [HTML](https://gist.github.com/jim-rosales/46f2f87823e2546e3e1da4427e72bb48) and [CSS](https://gist.github.com/jim-rosales/f7e0153c0bb6a2c9563d415b9b4d44dc) solution. The files will allow you to see an alternate way of completing the project while allowing you to see how you should indent your HTML and CSS files.

**Comment by xancbiz** [comment]
Thank you for reviewing my work and for your feedback Jim.  Just one question: is there any way to automatically indent the HTML? I am using the Atom text editor...

**Comment by jim-rosales** [comment]
I'm not too sure; I use Brackets, so I'm not very familiar with Atom. I did find this [resource](https://stackoverflow.com/questions/22611377/how-to-auto-indent-code-in-the-atom-editor) that might answer your question.
